# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: GitHub Actions for KERIA
on:
  push:
    branches:
      - "main"
      - "development"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-15, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
      - name: Config libsodium
        if: runner.os == 'macOS'
        run: |
          echo "SODIUM_INSTALL=system" >> $GITHUB_ENV
          echo "DYLD_LIBRARY_PATH=/opt/homebrew/lib:$DYLD_LIBRARY_PATH" >> $GITHUB_ENV
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.9.5"
      - name: Install dependencies
        run: make install-dev
      - name: Lint changes
        run: make lint
      - name: Check formatting
        run: make format-check
      - name: Run core KERIA tests
        run: make test

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run docker container
        # Ensure that the image can be built and started
        run: docker compose up --build --wait

  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.12.8
      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.9.5"
      - name: Install dependencies
        run: make install-dev
      - name: Run core KERIA tests
        run: make test-coverage
      - name: Upload
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
